"""
Engine-swap invariants: the reference and production engines satisfy the same
*engine-agnostic* oracle contracts.

The spec's design goal is that the production engine drops in wherever the
reference engine sits. For the **data-coupled** refinement invariants (categories
C/D/E/F) that swap is not literally one line — the oracle's synthetic data is
generated by the reference engine, so each engine must be validated against data
it generated itself (done in ``test_production_refine.py`` /
``test_production_parametric.py`` for the production engine, and
``test_invariants.py`` for the reference engine).

The invariants that ARE engine-agnostic — Protocol conformance, forward purity,
non-negativity, and self-consistency of the engine's own Jacobian against a
finite difference of its own forward model — are checked here against *both*
engines via parametrization. This is the concrete, sound expression of the
"swap the engine" claim.
"""

from __future__ import annotations

from dataclasses import replace

import numpy as np
import pytest

from aura import spec
from aura.engine.forward import ProductionEngine
from aura.reference import RefEngine
from aura.spec import (
    AtomSite,
    DataType,
    Histogram,
    Parameter,
    ParamKind,
    Phase,
    RefinementState,
    UnitCell,
)

A0 = 5.431
WL = 1.5406
SI = (
    AtomSite("Si", 0, 0, 0),
    AtomSite("Si", 0.5, 0.5, 0.5),
    AtomSite("Si", 0.5, 0.0, 0.5),
    AtomSite("Si", 0.0, 0.5, 0.5),
)


@pytest.fixture(params=[RefEngine, ProductionEngine], ids=["reference", "production"])
def any_engine(request):
    """Both engines, for the invariants that hold regardless of who made the data."""
    return request.param()


def _state():
    phase = Phase("Si", "Fd-3m", UnitCell(A0, A0, A0), SI)
    x = np.linspace(20.0, 120.0, 1200)
    h = Histogram(
        "h", DataType.CW_XRAY, x, np.zeros_like(x), np.ones_like(x), {}, wavelength=WL
    )
    params = (
        Parameter(
            "phase:Si:cell.a", ParamKind.PHASE, A0, vary=True, lower=5.0, upper=6.0
        ),
        Parameter(
            "hist:h:scale", ParamKind.HISTOGRAM, 1.0, vary=True, lower=1e-6, upper=1e6
        ),
        Parameter(
            "hist:h:bkg", ParamKind.HISTOGRAM, 5.0, vary=True, lower=0.0, upper=1e4
        ),
        Parameter(
            "hist:h:fwhm", ParamKind.HISTOGRAM, 0.3, vary=True, lower=0.05, upper=2.0
        ),
        Parameter("hist:h:eta", ParamKind.HISTOGRAM, 0.5, vary=False),
    )
    return RefinementState((phase,), (h,), params), h


def test_engine_conforms_to_all_protocols(any_engine):
    assert isinstance(any_engine, spec.ForwardModel)
    assert isinstance(any_engine, spec.ParametricEngine)
    assert isinstance(any_engine, spec.Minimizer)


def test_forward_is_pure(any_engine):
    st, h = _state()
    assert np.array_equal(any_engine.calculate(st, h), any_engine.calculate(st, h))


def test_forward_nonnegative(any_engine):
    st, h = _state()
    assert np.all(any_engine.calculate(st, h) >= 0.0)


def test_jacobian_matches_finite_difference(any_engine):
    """The engine's own Jacobian agrees with an independent central FD of its own
    forward model — the contract the Phase-6 autodiff backend must keep."""
    st, h = _state()
    J = any_engine.jacobian(st, h)
    varied = [p for p in st.parameters if p.vary]
    J_fd = np.zeros_like(J)
    for j, p in enumerate(varied):
        step = 1e-6 * max(abs(p.value), 1.0)
        up = replace(
            st,
            parameters=tuple(
                replace(q, value=q.value + step) if q.name == p.name else q
                for q in st.parameters
            ),
        )
        dn = replace(
            st,
            parameters=tuple(
                replace(q, value=q.value - step) if q.name == p.name else q
                for q in st.parameters
            ),
        )
        J_fd[:, j] = (any_engine.calculate(up, h) - any_engine.calculate(dn, h)) / (
            2 * step
        )
    for j in range(J.shape[1]):
        num = np.linalg.norm(J[:, j] - J_fd[:, j])
        den = np.linalg.norm(J_fd[:, j]) + 1e-30
        assert num / den < 1e-3, f"Jacobian column {j} disagrees with FD: {num/den:.2e}"
