"""
Production-engine refinement invariants (Phase 4).

Mirrors the oracle's refinement categories C/E/F/G, but with synthetic data
generated by the **production** engine itself (so the fit target matches the
model under test — the oracle's `_make_histogram` bakes in the *reference*
engine, so the production engine needs its own self-consistent fixtures). Full
parametrization of the shared oracle fixture over both engines is deferred to
Phase 5, when the real `ParametricEngine.expand` exists.
"""

from __future__ import annotations

from dataclasses import replace

import numpy as np
import pytest

from aura import spec
from aura.engine.forward import ProductionEngine
from aura.spec import (
    AtomSite,
    DataType,
    Histogram,
    Parameter,
    ParamKind,
    Phase,
    RefinementState,
    UnitCell,
)

RNG = np.random.default_rng(20260611)
WL = 1.909
A_TRUE = 5.9738

NABR = Phase(
    "NaBr",
    "F m -3 m",
    UnitCell(A_TRUE, A_TRUE, A_TRUE),
    (AtomSite("Na", 0, 0, 0), AtomSite("Br", 0.5, 0.5, 0.5)),
)
ENGINE = ProductionEngine()


def _truth_params(a, scale, bkg, fwhm):
    return (
        Parameter("phase:NaBr:cell.a", ParamKind.PHASE, a),
        Parameter("hist:h:scale", ParamKind.HISTOGRAM, scale),
        Parameter("hist:h:bkg", ParamKind.HISTOGRAM, bkg),
        Parameter("hist:h:fwhm", ParamKind.HISTOGRAM, fwhm),
        Parameter("hist:h:eta", ParamKind.HISTOGRAM, 0.5),
    )


def _make_data(a=A_TRUE, scale=2000.0, bkg=50.0, fwhm=0.4, noise=False) -> Histogram:
    """A NaBr CW-neutron histogram generated by the production engine."""
    x = np.linspace(20.0, 120.0, 2200)
    blank = Histogram(
        "h",
        DataType.CW_NEUTRON,
        x,
        np.zeros_like(x),
        np.ones_like(x),
        {},
        wavelength=WL,
    )
    y = ENGINE.calculate(
        RefinementState((NABR,), (blank,), _truth_params(a, scale, bkg, fwhm)), blank
    )
    if noise:
        y = y + RNG.normal(0.0, np.sqrt(np.clip(y, 1.0, None)))
    w = 1.0 / np.clip(y if not noise else np.abs(y), 1.0, None)
    return Histogram("h", DataType.CW_NEUTRON, x, y, w, {}, wavelength=WL)


def _seed(a, scale, bkg, fwhm, vary_a=True):
    return (
        Parameter(
            "phase:NaBr:cell.a", ParamKind.PHASE, a, vary=vary_a, lower=5.8, upper=6.1
        ),
        Parameter(
            "hist:h:scale", ParamKind.HISTOGRAM, scale, vary=True, lower=1e-3, upper=1e7
        ),
        Parameter(
            "hist:h:bkg", ParamKind.HISTOGRAM, bkg, vary=True, lower=0.0, upper=1e5
        ),
        Parameter(
            "hist:h:fwhm", ParamKind.HISTOGRAM, fwhm, vary=True, lower=0.05, upper=2.0
        ),
        Parameter("hist:h:eta", ParamKind.HISTOGRAM, 0.5, vary=False),
    )


def _refine(h, seed_params, **kw):
    st = RefinementState((NABR,), (h,), seed_params)
    return ENGINE.refine(st, ENGINE, ENGINE, seed=1, **kw)


def _a(res):
    return next(p for p in res.state.parameters if p.name == "phase:NaBr:cell.a")


# --- Protocol conformance ------------------------------------------------------


def test_production_engine_conforms_to_all_protocols():
    assert isinstance(ENGINE, spec.ForwardModel)
    assert isinstance(ENGINE, spec.ParametricEngine)
    assert isinstance(ENGINE, spec.Minimizer)


# --- C. Refinement correctness -------------------------------------------------


class TestRefinementCorrectness:

    def test_fixpoint_seeded_at_truth(self):
        h = _make_data(noise=False)
        res = _refine(h, _seed(A_TRUE, 2000.0, 50.0, 0.4), max_iter=50)
        assert abs(_a(res).value - A_TRUE) < 1e-4
        assert res.rwp < 1e-3

    def test_parameter_recovery_within_uncertainty(self):
        h = _make_data(a=5.99, noise=True)
        res = _refine(h, _seed(5.95, 1500.0, 40.0, 0.5), max_iter=120)
        p_a = _a(res)
        assert p_a.sigma is not None and p_a.sigma > 0
        n_sigma = abs(p_a.value - 5.99) / p_a.sigma
        assert n_sigma < spec.ACCEPTANCE["recovery_n_sigma"], f"{n_sigma:.2f} sigma off"

    def test_goodness_of_fit_calibration(self):
        h = _make_data(noise=True)
        res = _refine(h, _seed(A_TRUE, 2000.0, 50.0, 0.4), max_iter=120)
        assert (
            spec.ACCEPTANCE["gof_low"] < res.reduced_chi2 < spec.ACCEPTANCE["gof_high"]
        ), f"GoF {res.reduced_chi2:.3f} outside band"

    def test_refinement_is_deterministic(self):
        h = _make_data(a=5.97, noise=False)
        r1 = _refine(h, _seed(5.95, 1800.0, 45.0, 0.45), max_iter=50)
        r2 = _refine(h, _seed(5.95, 1800.0, 45.0, 0.45), max_iter=50)
        assert _a(r1).value == _a(r2).value


# --- E. Conservation & numerical guards ----------------------------------------


class TestConservationAndGuards:

    def test_refined_cell_stays_physical(self):
        h = _make_data(a=5.99, noise=True)
        res = _refine(h, _seed(5.95, 1500.0, 40.0, 0.5), max_iter=80)
        a = _a(res).value
        assert UnitCell(a, a, a).is_physical()

    def test_conditioning_reported(self):
        h = _make_data(noise=True)
        res = _refine(h, _seed(A_TRUE, 2000.0, 50.0, 0.4), max_iter=40)
        assert "condition_number" in res.diagnostics
        assert np.isfinite(res.diagnostics["condition_number"])

    def test_zero_weight_points_ignored(self):
        h = _make_data(a=5.99, noise=False)
        y = h.y_obs.copy()
        w = h.weights.copy()
        y[200:260] = 1e7  # gross corruption...
        w[200:260] = 0.0  # ...but masked out
        h2 = replace(h, y_obs=y, weights=w)
        res = _refine(h2, _seed(5.95, 1800.0, 45.0, 0.45), max_iter=80)
        assert abs(_a(res).value - 5.99) < 1e-2, "masked corruption leaked into the fit"


# --- F. False-minimum / seed-quality discipline --------------------------------


class TestSeedDiscipline:

    def test_metrics_present_and_sane(self):
        h = _make_data(noise=True)
        res = _refine(h, _seed(A_TRUE, 2000.0, 50.0, 0.4), max_iter=80)
        assert res.rwp >= 0.0
        assert res.reduced_chi2 > 0.0
        assert res.reduced_chi2 < 5.0

    def test_grossly_wrong_fixed_model_yields_poor_rwp(self):
        h = _make_data(a=A_TRUE, noise=False)
        # Cell pinned far away and not allowed to vary: a deliberately wrong model.
        seed = _seed(6.05, 2000.0, 50.0, 0.4, vary_a=False)
        res = _refine(h, seed, max_iter=60)
        assert res.rwp > 0.05, f"a wrong fixed cell must fit poorly, rwp={res.rwp:.3f}"


# --- G. State & provenance -----------------------------------------------------


class TestStateAndProvenance:

    def test_refinement_records_provenance_and_log(self):
        h = _make_data(noise=False)
        res = _refine(h, _seed(A_TRUE, 2000.0, 50.0, 0.4), max_iter=20)
        assert res.provenance is not None
        assert res.provenance.kernel_backend == "production-trf"
        assert res.provenance.random_seed == 1
        assert any("refined" in m for m in res.state.provenance)

    def test_profiling_diagnostics_present(self):
        h = _make_data(noise=False)
        res = _refine(h, _seed(A_TRUE, 2000.0, 50.0, 0.4), max_iter=20)
        for key in ("wall_time_s", "n_forward_evals", "peak_rss_mb", "n_points"):
            assert key in res.diagnostics
        assert res.diagnostics["n_forward_evals"] > 0


# --- First real Rietveld fit (PbSO4 CW neutron, the IUCr round-robin) ----------

from pathlib import Path  # noqa: E402

import aura.io as io  # noqa: E402
from aura.bridge import state_to_histograms  # noqa: E402

DATA_DIR = Path(__file__).parent.parent / "testDataGsas"


class TestRealRietveld:

    @pytest.fixture(autouse=True)
    def _require_data(self):
        if not DATA_DIR.is_dir():
            pytest.skip("Test data directory not found")

    def test_pbso4_cw_neutron_refines(self):
        """Refine real PbSO4/D1A CW-neutron data: the minimizer converges, reduces
        Rwp, and recovers the orthorhombic lattice to the reference within
        uncertainty with a physical cell. (Absolute Rwp is limited by the flat-
        background / single-width model until Phase 7; the high GoF correctly
        flags that model inadequacy — the R-factor-non-oracle rule.)"""
        ph = io.read(DATA_DIR / "PbSO4.cif", "phase")
        h = state_to_histograms(io.read(DATA_DIR / "PBSO4.CWN", "powder"))[0]
        c = ph.cell
        seed = (
            Parameter(
                f"phase:{ph.name}:cell.a",
                ParamKind.PHASE,
                c.a,
                vary=True,
                lower=c.a - 0.2,
                upper=c.a + 0.2,
            ),
            Parameter(
                f"phase:{ph.name}:cell.b",
                ParamKind.PHASE,
                c.b,
                vary=True,
                lower=c.b - 0.2,
                upper=c.b + 0.2,
            ),
            Parameter(
                f"phase:{ph.name}:cell.c",
                ParamKind.PHASE,
                c.c,
                vary=True,
                lower=c.c - 0.2,
                upper=c.c + 0.2,
            ),
            Parameter(
                f"hist:{h.id}:scale",
                ParamKind.HISTOGRAM,
                5e-4,
                vary=True,
                lower=1e-8,
                upper=1e2,
            ),
            Parameter(
                f"hist:{h.id}:bkg",
                ParamKind.HISTOGRAM,
                float(np.median(h.y_obs)),
                vary=True,
                lower=0.0,
                upper=1e4,
            ),
            Parameter(
                f"hist:{h.id}:fwhm",
                ParamKind.HISTOGRAM,
                0.35,
                vary=True,
                lower=0.1,
                upper=1.0,
            ),
            Parameter(f"hist:{h.id}:eta", ParamKind.HISTOGRAM, 0.5, vary=False),
        )
        st = RefinementState((ph,), (h,), seed)
        rwp_seed = spec.rwp(h.y_obs, ENGINE.calculate(st, h), h.weights)
        res = ENGINE.refine(st, ENGINE, ENGINE, max_iter=80, seed=1)

        assert res.converged
        assert res.rwp < rwp_seed  # refinement improved the fit
        # Lattice recovered close to the reference cell, with real uncertainties.
        refined = {p.name: p for p in res.state.parameters}
        for axis, ref in (("a", c.a), ("b", c.b), ("c", c.c)):
            p = refined[f"phase:{ph.name}:cell.{axis}"]
            assert abs(p.value - ref) < 0.05
            assert p.sigma is not None and p.sigma > 0
        a, b, cc = (
            refined[f"phase:{ph.name}:cell.{ax}"].value for ax in ("a", "b", "c")
        )
        assert UnitCell(a, b, cc, 90, 90, 90).is_physical()
        assert np.isfinite(res.reduced_chi2)
        assert res.provenance is not None and res.provenance.input_data_hash
